services:
  app:
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - 3000
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always 
    ports:
      - 3306
    expose:
      - 3306
      - 33060
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'  
volumes:
  db-data: